# Generated by Django 5.2.1 on 2025-05-09 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-likes'], 'verbose_name': 'Artiste', 'verbose_name_plural': 'Artistes'},
        ),
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Beat', 'verbose_name_plural': 'Beats'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-release_date'], 'verbose_name': 'Chanson', 'verbose_name_plural': 'Chansons'},
        ),
        migrations.AddField(
            model_name='artist',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_artists', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs ayant liké'),
        ),
        migrations.AddField(
            model_name='beat',
            name='users_who_bought',
            field=models.ManyToManyField(blank=True, related_name='purchased_beats', to=settings.AUTH_USER_MODEL, verbose_name='Acheté par'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(help_text='Format carré recommandé', upload_to='artists/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_media_link',
            field=models.URLField(blank=True, verbose_name='Lien réseaux sociaux'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(help_text='Format MP3 recommandé', upload_to='beats/', verbose_name='Fichier audio'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist', verbose_name='Artiste'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(help_text='Format MP3 recommandé', upload_to='songs/', verbose_name='Fichier audio'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
