# Generated by Django 5.2.1 on 2025-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_options_alter_beat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
    ]
